kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.34.3
- role: worker
  image: kindest/node:v1.34.3
- role: worker
  image: kindest/node:v1.34.3
- role: worker
  image: kindest/node:v1.34.3
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP


# commands
# kind create cluster --name=iamsnyg-cluster --config=kind-cluster-config.yml
# After creating the kind cluster
# kubectl cluster-info --context kind-iamsnyg-cluster
  